#!/bin/sh
# author: DQB
# How to use ?
# 1.将该脚本和pngquant脚本放在工程的根目录下
# 2.cd到工程的根目录下，执行 ./tinyImage 即可

echo "Starting compress images, please wait a minite..."
for var in `find . -name "*.png"`
do
  # 压缩图片，并且替换源文件
  ./pngquant --ext .png --force  -- $var
done
echo "Task Complete!"